set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)

set (RISCV_PREFIX "riscv32-unknown-elf-" CACHE STRING "RISC-V Toolchain Prefix")

set(CMAKE_C_COMPILER   "${RISCV_PREFIX}gcc")
set(CMAKE_ASM_COMPILER "${RISCV_PREFIX}gcc")
set(CMAKE_OBJCOPY      "${RISCV_PREFIX}objcopy")
set(CMAKE_OBJDUMP      "${RISCV_PREFIX}objdump")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
